version: '5.5.0'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnectionString=Host=172.18.0.2;Port=5432;Username=guru;Password=gurucharan;Database=guru;TrustServerCertificate=True;
      - postgres
  postgres:
    container_name: container-pg
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: guru
      POSTGRES_PASSWORD: gurucharan
      POSTGRES_DB: guru
      
    volumes:
      - local_pgdata:/var/lib/postgresql
    restart: always

volumes:
  postgres-data:
  local_pgdata:
  